# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.version)

<module 'numpy.version' from '/home/kodolamacz/anaconda3/lib/python3.7/site-packages/numpy/version.py'>


In [5]:
print(np.__version__)

1.15.1


#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
v = np.zeros(10)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [11]:
v.size

10

In [14]:
u = np.zeros((5,10))
u

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
u.size

50

In [16]:
u.itemsize

8

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [18]:
w = np.zeros(10)
w[4] = 1
w

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [20]:
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [36]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [42]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [45]:
lst = [1,2,0,0,4,0]
v = np.nonzero(lst)
v

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [3]:
# macierz jednostkowa 3 x 3
i = np.array([[1,0,0], [0,1,0], [0,0,1]])
i

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [9]:
j = np.zeros((3,3))
for k in range(3):
    j[k,k] = 1
j

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# macierz jednostkowa nxn
n = 15
j = np.zeros((n,n))
for k in range(n):
    j[k,k] = 1
j

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
a1 = np.random.randint(5,100,27)
a1.reshape(3,3,3)

array([[[52, 74, 32],
        [44, 18, 43],
        [33, 41,  6]],

       [[95, 31, 35],
        [96, 71, 68],
        [50, 69, 73]],

       [[50, 71, 29],
        [56, 54, 85],
        [37, 55, 83]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
a2 = np.random.randint(0,1000,100).reshape(10,10)
a2

array([[221, 481, 601,  59, 128,  86, 333, 684, 173, 265],
       [396, 397, 477, 841, 777, 846, 299, 499, 978, 749],
       [913,   6,  45, 592, 231, 876,  21, 392,  12, 980],
       [493, 617, 663, 866, 986,  15, 188, 193, 470, 576],
       [637, 891,  52, 248, 319, 395, 254, 547, 136, 235],
       [246, 749, 714, 898, 231,  46, 105, 581, 120, 322],
       [462,  11,  85, 109, 589, 575, 648, 987, 487, 364],
       [630, 434, 984,  51, 125, 182, 509, 747, 140, 665],
       [106, 114, 234, 638, 386, 594,  39,  99, 188, 420],
       [972, 995, 884, 287, 987,  78, 162, 425,  80, 339]])

In [27]:
print('minimum value: ', a2.min())
print('maximum value: ', a2.max())
print('mean value: ', a2.mean())
print('sum of values: ', a2.sum())

minimum value:  6
maximum value:  995
mean value:  429.62
sum of values:  42962


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [28]:
v1 = np.random.randint(100, 500, 30)
v1

array([300, 302, 184, 358, 173, 201, 249, 431, 153, 352, 436, 399, 381,
       134, 325, 150, 204, 412, 364, 107, 406, 277, 466, 397, 418, 424,
       410, 383, 163, 375])

In [29]:
len(v1)

30

In [32]:
print('mean vector value: ', v1.mean())

mean vector value:  311.1333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [75]:
# macierz wymiaru k x k - KWADRATOWA
k = 13
a3 = np.zeros((k,k))
a3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
for n in range(k):
    a3[n, 0] = 1
    a3[n, k-1] = 1
    a3[0, n] = 1
    a3[k-1, n] = 1
a3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [87]:
# macierz wymiaru k x l - NIEKWADRATOWA
k = 13
l = 16
a5 = np.zeros((k,l))
a5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [88]:
for n in range(k):
    a5[n, 0] = 1
    a5[n, l-1] = 1
for m in range(l):
    a5[0, m] = 1
    a5[k-1, m] = 1
a5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [93]:
a4 = a1.reshape(9,3)
a4

array([[52, 74, 32],
       [44, 18, 43],
       [33, 41,  6],
       [95, 31, 35],
       [96, 71, 68],
       [50, 69, 73],
       [50, 71, 29],
       [56, 54, 85],
       [37, 55, 83]])

In [124]:
a5 = np.zeros(55).reshape(11,5)

# for n in range(1,10):
#     a5[n, 1] = a4[n-1, 0]
#     a5[n, 2] = a4[n-1, 1]
#     a5[n, 3] = a4[n-1, 2]
for n in range(1,10):
    for k in range(1,4):
        a5[n,k] = a4[n-1, k-1]
    
a5

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0., 52., 74., 32.,  0.],
       [ 0., 44., 18., 43.,  0.],
       [ 0., 33., 41.,  6.,  0.],
       [ 0., 95., 31., 35.,  0.],
       [ 0., 96., 71., 68.,  0.],
       [ 0., 50., 69., 73.,  0.],
       [ 0., 50., 71., 29.,  0.],
       [ 0., 56., 54., 85.,  0.],
       [ 0., 37., 55., 83.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [125]:
# macierz użytkownika otoczona zerami
rows_number = int(input('podaj liczbę wierszy: '))
cols_number = int(input('podaj liczbę kolumn: '))
all_number = rows_number * cols_number
all_zeros = (rows_number+2) * (cols_number+2)
a7 = np.random.randint(10,99, all_number).reshape(rows_number, cols_number)
a8 = np.zeros(all_zeros).reshape(rows_number + 2, cols_number + 2)
for n in range(1,rows_number+1):
    for k in range(1, cols_number+1):
        a8[n,k] = a7[n-1, k-1]
a8

podaj liczbę wierszy: 6
podaj liczbę kolumn: 9


array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 10., 89., 10., 32., 90., 65., 90., 62., 32.,  0.],
       [ 0., 62., 20., 95., 98., 51., 23., 72., 13., 50.,  0.],
       [ 0., 17., 70., 44., 55., 94., 14., 89., 46., 26.,  0.],
       [ 0., 38., 38., 44., 28., 27., 92., 96., 13., 88.,  0.],
       [ 0., 86., 56., 30., 27., 49., 22., 12., 28., 39.,  0.],
       [ 0., 93., 27., 44., 10., 98., 58., 80., 63., 71.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [131]:
np.nan

nan

In [129]:
np.inf

inf

In [127]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)


nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [147]:
a9 = np.random.randint(1,5,25).reshape(5,5)
for k in range(5):
    a9[0,k+0:5] = 0
    a9[1,k+1:5] = 0
    a9[2,k+2:5] = 0
    a9[3,k+3:5] = 0
    a9[4,k+4:5] = 0
a9

array([[0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0],
       [4, 3, 0, 0, 0],
       [3, 3, 2, 0, 0],
       [1, 4, 1, 2, 0]])

In [149]:
# bardziej ogolny sposob dla macierzy wymiaru n x n
n = int(input('podaj wymiar macierzy: '))
a10 = np.random.randint(1,5,n**2).reshape(n,n)
for k in range(n):
    for w in range(n):
        a10[w,k+w:n] = 0
a10        

podaj wymiar macierzy: 12


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 4, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 4, 4, 3, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 3, 2, 1, 3, 0, 0, 0, 0, 0, 0],
       [1, 1, 3, 1, 4, 4, 4, 0, 0, 0, 0, 0],
       [2, 4, 4, 3, 1, 4, 2, 1, 0, 0, 0, 0],
       [4, 3, 4, 3, 2, 4, 3, 3, 2, 0, 0, 0],
       [3, 2, 3, 1, 3, 1, 3, 4, 3, 3, 0, 0],
       [2, 4, 3, 4, 2, 3, 4, 4, 2, 2, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [170]:
# macierz wypełniona wzorem szachownicy
a11 = np.zeros(64).reshape(8,8)

for k in range(4):
    a11[0, 2*k] = 1
    a11[2, 2*k] = 1
    a11[4, 2*k] = 1
    a11[6, 2*k] = 1
    a11[1, 2*k+1] = 1
    a11[3, 2*k+1] = 1
    a11[5, 2*k+1] = 1
    a11[7, 2*k+1] = 1
    
a11
    

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [226]:
# macierz szachownica wymiaru n x n
n = int(input('podaj wymiar macierzy: '))

a13 = np.zeros(n**2).reshape(n,n)

parzyste = []
nieparzyste = []
#tutaj zero zaliczone jako liczba parzysta!!

for x in range(n):
    if x % 2 == 0:
        parzyste.append(x)
    else:
        nieparzyste.append(x)

# do dalszych obliczen potrzebne n/2, ale n2 to float
if n % 2 == 0:
    m = int(n/2)

else:
    m = int(n/2)+1

            
for k in range(m):
    for w_parz in parzyste:
        a13[w_parz, 2*k] = 1

    for w_nieparz in nieparzyste:
        if n % 2 == 0:
            a13[w_nieparz, 2*k+1] = 1
        else:
            a13[w_nieparz, 2*k-1] = 1
            a13[w_nieparz, -1] = 0
            
a13

podaj wymiar macierzy: 15


array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.

In [228]:
# ćwiczenia własne - różne
a14 = np.ones((5,5))
a14

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [240]:
# macierz z wartościami poniżej głownej przekątnej
a15 = np.diag(1+np.arange(9),k=-1)
a15

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9, 0]])

In [241]:
# macierz diagonalna
a16 = np.diag(1+np.arange(9))
a16

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [242]:
# macierz jednostkowa
a17 = np.eye(9)
a17

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [243]:
# array długości 6*7*8 = 336 elementów, szukamy współrzędnych elementu nr 100
np.unravel_index(100, (6,7,8))

(1, 5, 4)

In [244]:
# tutaj przykład ze stackoverflow -> array 42 elementy, ułożony w 7 wierszy, 6 kolumn, szukamy elementów nr 22,41,37 czyli
# w macierzy o współrzędnych (3,4), (6,1), (6,5) - zatem skąd wynik????
np.unravel_index([22,41,37], (7,6))

(array([3, 6, 6]), array([4, 5, 1]))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [15]:
a18 = [0,1]
np.tile(a18, (4,8))

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

In [17]:
a19 = [[0,1],[2,3],[4,5]]
np.tile(a19, (3,7))

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3],
       [4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3],
       [4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3],
       [4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5]])

In [19]:
a20 = [[0,1],[1,0]]
np.tile(a20,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
a21 = np.random.randint(1,100,25).reshape(5,5)
a21

array([[41,  7, 82, 82, 91],
       [ 7,  5, 94, 71, 98],
       [43, 91, 82, 38, 76],
       [32,  5, 66, 43,  9],
       [69, 53, 73, 25, 15]])

In [25]:
a21_min = a21.min()
a21_max = a21.max()
print(a21_min, a21_max)
# macierz znormalizowana
a21_norm = (a21 - a21_min)/(a21_max - a21_min)
a21_norm

5 98


array([[0.38709677, 0.02150538, 0.82795699, 0.82795699, 0.92473118],
       [0.02150538, 0.        , 0.95698925, 0.70967742, 1.        ],
       [0.40860215, 0.92473118, 0.82795699, 0.35483871, 0.76344086],
       [0.29032258, 0.        , 0.65591398, 0.40860215, 0.04301075],
       [0.68817204, 0.51612903, 0.7311828 , 0.21505376, 0.10752688]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [103]:
# nie rozumiem polecenia

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [34]:
a22 = np.random.randint(1,10,15).reshape(5,3)
a22

array([[2, 1, 9],
       [1, 3, 7],
       [4, 4, 2],
       [1, 4, 2],
       [3, 4, 4]])

In [35]:
a23 = np.random.randint(1,10,6).reshape(3,2)
a23

array([[5, 6],
       [3, 6],
       [6, 2]])

In [39]:
# mnożenie macierzy
a22 @ a23

array([[67, 36],
       [56, 38],
       [44, 52],
       [29, 34],
       [51, 50]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [52]:
a24 = np.random.randint(1,10,20)
a24

array([7, 2, 3, 9, 3, 4, 3, 6, 5, 9, 7, 2, 7, 4, 2, 3, 2, 2, 5, 9])

In [55]:
new_a24 = []
for a in a24:
    if a >= 3 and a<=8:
        a = -a
        print(a)
    new_a24.append(a)

np.array(new_a24)

-7
-3
-3
-4
-3
-6
-5
-7
-7
-4
-3
-5


array([-7,  2, -3,  9, -3, -4, -3, -6, -5,  9, -7,  2, -7, -4,  2, -3,  2,
        2, -5,  9])

In [64]:
# drugi sposób
a25 = np.random.randint(1,10,20)
# a25[(a25 >=3) & (a25<=8)] *= -1
a25[(a25 >=3) & (a25<=8)] = a25[(a25 >=3) & (a25<=8)] * (-1)
a25

array([-8,  1,  1,  9,  1, -3, -6,  1, -6,  1, -5, -7,  9, -3,  2, -8,  9,
       -4,  1, -6])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [68]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
# po pierwszym wywołaniu wychodzi 9, 10 po drugim 10,10 - ???

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [83]:
Z = np.array([2,3,8,9,1,4])
print(Z)
# Z**Z ozn. 2**2, 3**3, 8**8, 9**9, 1**1, 4**4
print(Z**Z)
# 2**1, 2**2, 2**7, 2**8, 2**0, 2**3
print(2 << Z >> 2)
# badanie czy element mniejszy niż minus ten element
print(Z <- Z)
# zapis z jednostkami - tutaj razy 2 jedn.
print(2j*Z)
# dzielone przez 2 a nastepnie przez 2
print(Z/2/2)
# print(Z<Z>Z) - nie działa ????

[2 3 8 9 1 4]
[        4        27  16777216 387420489         1       256]
[  2   4 128 256   1   8]
[False False False False False False]
[0. +4.j 0. +6.j 0.+16.j 0.+18.j 0. +2.j 0. +8.j]
[0.5  0.75 2.   2.25 0.25 1.  ]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [85]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/home/kodolamacz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/home/kodolamacz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [101]:
# nie rozumiem polecenia

a29 = np.random.uniform(-10,10,10)
print(a29)
# ceil = część całkowita górna (sufit)
print('sufit', np.ceil(a29))
# floor = część całkowita dolna (podłoga)
print('podłoga', np.floor(a29))
# abs = wartość bezwzględna
print('podłoga z wart. bezwzgl.', np.ceil(abs(a29)))
# copysign = kopiuje znak z oryginalnej a29 do wyniku 
print(np.copysign(np.ceil(abs(a29)), a29))

[ 1.21808338  2.20728371  0.53499757 -5.65823947 -8.70649511  3.93463292
 -4.17410168 -0.92479705 -1.83357529  8.16654402]
sufit [ 2.  3.  1. -5. -8.  4. -4. -0. -1.  9.]
podłoga [ 1.  2.  0. -6. -9.  3. -5. -1. -2.  8.]
podłoga z wart. bezwzgl. [2. 3. 1. 6. 9. 4. 5. 1. 2. 9.]
[ 2.  3.  1. -6. -9.  4. -5. -1. -2.  9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [88]:
# wartości wspólne w 2 arrayach - intersect1d
a26 = np.arange(1,30,2)
a27 = np.arange(10,40,3)
print(a26, a27)
a28 = np.intersect1d(a26,a27)
print(a28)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29] [10 13 16 19 22 25 28 31 34 37]
[13 19 25]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [107]:
# nie rozumiem???

defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
Z

array([inf])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [110]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [119]:
today = np.datetime64('today')
yesterday = today - 1
tomorrow = today +1
print('today: ', today, 'yesterday: ', yesterday, 'tomorrow: ', tomorrow)

today:  2018-12-26 yesterday:  2018-12-25 tomorrow:  2018-12-27


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [125]:
july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
july_2016

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [127]:
A = np.array([2,4,6,8,-10])
B = np.array([3,6,9,-2,5])
print((A+B)*(-A/2))

[ -5. -20. -45. -24. -25.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [137]:
a27 = np.random.uniform(-5,15,10)
print(a27)
print(np.ceil(a27))
print(np.floor(a27))
print(np.round(a27))

[ 2.34905951e+00  3.17164966e+00  3.76852370e+00  8.90613862e+00
  8.92215698e-01  1.30155516e+01 -7.73596135e-03  1.21429344e+01
  5.65477373e+00  2.79101254e+00]
[ 3.  4.  4.  9.  1. 14. -0. 13.  6.  3.]
[ 2.  3.  3.  8.  0. 13. -1. 12.  5.  2.]
[ 2.  3.  4.  9.  1. 13. -0. 12.  6.  3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [142]:
a28 = np.random.randint(0,5,25).reshape(5,5)
a28

array([[4, 4, 3, 0, 1],
       [3, 0, 4, 0, 3],
       [1, 3, 4, 3, 2],
       [3, 0, 0, 3, 1],
       [1, 0, 0, 4, 3]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [152]:
import random
def integer_generator(number):
    int = []
    i = 0
    while i < number:
        r = random.randint(10,50)
        int.append(r)
        i += 1
    return int


a29 = np.array(integer_generator(10))
a29


array([47, 23, 38, 33, 18, 44, 17, 13, 35, 34])

In [164]:
# drugi sposob obiekt generator
def generator():
    for i in range(10,56,5):
        yield i

a30 = np.fromiter(generator(), dtype=int)
print(a30, type(a30))

print(generator())

[10 15 20 25 30 35 40 45 50 55] <class 'numpy.ndarray'>
<generator object generator at 0x7ff27063c0c0>


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [168]:
v1 = np.random.random(8)
v2 = np.zeros(10)
v2[-1] = 1
v2[1:9] = v1[0:8]
v2

array([0.        , 0.39261051, 0.13574734, 0.08724389, 0.40652505,
       0.5011024 , 0.1030859 , 0.07560929, 0.21916523, 1.        ])

In [171]:
# drugi sposób
v3 = np.linspace(0,1,num=10, endpoint=True)
v3

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [177]:
v4 = np.random.randint(-50,50,10)
v4.sort()
v4

array([-50, -35, -34, -28, -24, -14,  -7,  13,  17,  24])

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)