In [1]:
import numpy as np

In [2]:
np.random.seed(100)

In [6]:
# losowych 10 liczb z przedziału (0;1) - tablica 10x1
np.random.rand(10)

array([0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606,
       0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ])

In [13]:
# 1 losowa liczba z zakresu 0-99
np.random.randint(100)

84

In [14]:
# 10 losowych liczb z zakresu 0-99
los = []
for i in range(11):
    los.append(np.random.randint(100))
print(los)

[79, 10, 87, 60, 3, 48, 52, 43, 36, 5, 71]


In [16]:
# tablica 10x2
np.random.rand(10,2) 

array([[0.0920556 , 0.46349802],
       [0.50869889, 0.08846017],
       [0.52803522, 0.99215804],
       [0.39503593, 0.33559644],
       [0.80545054, 0.75434899],
       [0.31306644, 0.63403668],
       [0.54040458, 0.29679375],
       [0.1107879 , 0.3126403 ],
       [0.45697913, 0.65894007],
       [0.25425752, 0.64110126]])

In [18]:
np.random.rand(10,4) 

array([[0.50061432, 0.44517663, 0.09043279, 0.27356292],
       [0.9434771 , 0.02654464, 0.03999869, 0.28314036],
       [0.58234417, 0.9908928 , 0.99264224, 0.99311737],
       [0.11004833, 0.66448145, 0.52398683, 0.17314991],
       [0.94296024, 0.24186009, 0.99893227, 0.58269382],
       [0.183279  , 0.38684542, 0.18967353, 0.41077067],
       [0.59468007, 0.71658609, 0.48689148, 0.30958982],
       [0.57744137, 0.44170782, 0.3596781 , 0.32133193],
       [0.20820724, 0.45125862, 0.49184291, 0.89907631],
       [0.72936046, 0.77008977, 0.37543925, 0.34373954]])

In [3]:
np.random.rand(4,10) 

array([[0.20960895, 0.06598583, 0.46971574, 0.41331923, 0.68045382,
        0.19886028, 0.58796791, 0.41677644, 0.21528931, 0.96136796],
       [0.31888487, 0.38191909, 0.58337992, 0.71468122, 0.50702628,
        0.46945882, 0.65090218, 0.81140648, 0.03246606, 0.16972192],
       [0.16700202, 0.12974039, 0.88445221, 0.43593779, 0.0554911 ,
        0.31728139, 0.43949404, 0.91862785, 0.57977764, 0.6163658 ],
       [0.88085524, 0.05808064, 0.76703127, 0.60152519, 0.74210887,
        0.36943553, 0.85403821, 0.61067394, 0.11534612, 0.16682522]])

In [4]:
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [6]:
arr2 = np.arange(50)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [8]:
arr2.clip(min=5, max=25)

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [19]:
arr2

array([21, 36, 28, 23, 18, 15,  9,  2, 12, 41, 46, 34,  8, 26, 20,  5,  1,
       37, 22, 14, 35,  0, 27, 49, 16, 32, 25, 39, 29, 24,  6, 17, 19, 11,
       44, 40, 47,  3, 30, 13, 33, 45, 43, 48,  7, 10, 31, 38,  4, 42])

In [10]:
arr2.mean()

24.5

In [12]:
arr2.max()

49

In [14]:
arr2.size

50

In [21]:
# tablica z zakresu 0-60 o podanym rozkładzie wierszy i kolumn
arr3 = np.arange(60).reshape(15,4)

In [22]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [23]:
# przemieszanie wierszy tablicy
np.random.shuffle(arr3)

In [24]:
arr3

array([[36, 37, 38, 39],
       [44, 45, 46, 47],
       [56, 57, 58, 59],
       [32, 33, 34, 35],
       [48, 49, 50, 51],
       [ 4,  5,  6,  7],
       [52, 53, 54, 55],
       [16, 17, 18, 19],
       [ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [40, 41, 42, 43],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [34]:
# wielomiany Ax^3 + Bx^2 +Cx + D
# szuka wielomianu, którego pierwiastkiem jest 15 -> 1x - 15
np.poly(15)

array([  1., -15.])

In [59]:
np.poly([2,-5])
# szuka wielomianu, którego pierwiastkami są 2 i -5

array([  1.,   3., -10.])

In [62]:
# (x-2)(x-10)(x-15)(x+4)
# x^4 - 23 x^3 + 92 x^2 + 500 x - 1200
np.poly([2,10,15,-4])

array([ 1.0e+00, -2.3e+01,  9.2e+01,  5.0e+02, -1.2e+03])

In [63]:
# (x-2)(x-3)(x-5)(x+4)
# x^4 - 6 x^3 - 9 x^2 + 94 x - 120
np.poly([2,3,5,-4])

array([   1.,   -6.,   -9.,   94., -120.])

In [64]:
# szuka pierwiastków wielomianu o podanych współczynnikach
np.roots([1,-6,-9,94,-120])

array([-4.,  5.,  3.,  2.])

In [65]:
np.roots([1,-23,92,500,-1200])

array([15., 10., -4.,  2.])

In [70]:
# wartość wielomianu W w punkcie 5, tzn W(5)= 5^2 + 2*5 + 1
np.polyval([1, 2, 1], 5)

36

In [76]:
# zapisywanie array
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.array([[1,2,3,4,5,6]])

array([[1, 2, 3, 4, 5, 6]])

In [78]:
np.array([[1,2,3,4,5,6]],float)

array([[1., 2., 3., 4., 5., 6.]])

In [81]:
# tworzenie array 
np.arange(3,20)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [88]:
a1 = np.arange(4,20).reshape(4,4)
a1

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [92]:
np.random.shuffle(a1)
a1

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [93]:
a1[1]

array([4, 5, 6, 7])

In [94]:
a1[1][2]

6

In [95]:
len(a1)

4

In [96]:
len(np.arange(3,20))

17

In [23]:
import random
lst = []
for i in range(64):
    lst.append(random.randint(0,64)) 
    
print(lst)

[32, 45, 3, 59, 31, 6, 20, 14, 47, 60, 31, 48, 13, 31, 1, 27, 52, 35, 23, 49, 20, 9, 17, 56, 16, 16, 0, 0, 26, 27, 21, 21, 37, 40, 25, 26, 23, 25, 49, 38, 2, 46, 53, 21, 18, 33, 8, 42, 38, 0, 43, 8, 39, 45, 39, 61, 40, 23, 61, 60, 22, 7, 32, 2]


In [26]:
new_arr = np.array(lst).reshape(8,8)
new_arr

array([[32, 45,  3, 59, 31,  6, 20, 14],
       [47, 60, 31, 48, 13, 31,  1, 27],
       [52, 35, 23, 49, 20,  9, 17, 56],
       [16, 16,  0,  0, 26, 27, 21, 21],
       [37, 40, 25, 26, 23, 25, 49, 38],
       [ 2, 46, 53, 21, 18, 33,  8, 42],
       [38,  0, 43,  8, 39, 45, 39, 61],
       [40, 23, 61, 60, 22,  7, 32,  2]])

In [27]:
len(new_arr)

8

In [28]:
new_arr.tolist()

[[32, 45, 3, 59, 31, 6, 20, 14],
 [47, 60, 31, 48, 13, 31, 1, 27],
 [52, 35, 23, 49, 20, 9, 17, 56],
 [16, 16, 0, 0, 26, 27, 21, 21],
 [37, 40, 25, 26, 23, 25, 49, 38],
 [2, 46, 53, 21, 18, 33, 8, 42],
 [38, 0, 43, 8, 39, 45, 39, 61],
 [40, 23, 61, 60, 22, 7, 32, 2]]

In [30]:
new_arr.transpose()

array([[32, 47, 52, 16, 37,  2, 38, 40],
       [45, 60, 35, 16, 40, 46,  0, 23],
       [ 3, 31, 23,  0, 25, 53, 43, 61],
       [59, 48, 49,  0, 26, 21,  8, 60],
       [31, 13, 20, 26, 23, 18, 39, 22],
       [ 6, 31,  9, 27, 25, 33, 45,  7],
       [20,  1, 17, 21, 49,  8, 39, 32],
       [14, 27, 56, 21, 38, 42, 61,  2]])

In [36]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
b = np.arange(100,112).reshape(3,4)
b

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [37]:
a+b

array([[100, 102, 104, 106],
       [108, 110, 112, 114],
       [116, 118, 120, 122]])

In [38]:
a-b

array([[-100, -100, -100, -100],
       [-100, -100, -100, -100],
       [-100, -100, -100, -100]])

In [39]:
# mnożenie skalarne a11 * b11; a12 * b12 itd
a*b 

array([[   0,  101,  204,  309],
       [ 416,  525,  636,  749],
       [ 864,  981, 1100, 1221]])

In [41]:
a/b

array([[0.        , 0.00990099, 0.01960784, 0.02912621],
       [0.03846154, 0.04761905, 0.05660377, 0.06542056],
       [0.07407407, 0.08256881, 0.09090909, 0.0990991 ]])

In [44]:
b/(a+1) #nie mozna dzielic przez zero 

array([[100.        ,  50.5       ,  34.        ,  25.75      ],
       [ 20.8       ,  17.5       ,  15.14285714,  13.375     ],
       [ 12.        ,  10.9       ,  10.        ,   9.25      ]])

In [45]:
b ** a

array([[          1,         101,       10404,     1092727],
       [  116985856,  -122086263,  1179904576, -2089615005],
       [-1193213952,   859279629, -1093385216,  1591520719]], dtype=int32)

In [46]:
b % 5

array([[0, 1, 2, 3],
       [4, 0, 1, 2],
       [3, 4, 0, 1]], dtype=int32)

In [49]:
np.concatenate((a,b))

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [53]:
# mnożenie macierzy
print('a = ',a)
print('b = ', b.transpose())
a @ b.transpose()

a =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b =  [[100 104 108]
 [101 105 109]
 [102 106 110]
 [103 107 111]]


array([[ 614,  638,  662],
       [2238, 2326, 2414],
       [3862, 4014, 4166]])

In [38]:
kw = []
for i in range(0,9):
    kw.append(i**2)
print(kw)
c = np.array(kw).reshape(3,3)
print(c)

[0, 1, 4, 9, 16, 25, 36, 49, 64]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [13]:
d= np.sqrt(c)
d

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [18]:
int(d[2,2])

8

In [45]:
d2 = np.matrix(c)
print(d2)
np.linalg.det(d2)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


-216.00000000000006

In [26]:
d = np.array([1,2,3,4,5], float)
e = np.array([6,7,8,9,10], float)

In [27]:
# mnożenie d * e na poszczegolnych miejscach tj. 1*6 + 2*7 + 3*8 +4*9 +5*10
np.dot(d,e) 

130.0

In [28]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)

In [29]:
np.dot(a,c)

array([[ 4.,  0.],
       [14.,  2.]])

In [30]:
np.dot(a,b)

array([ 3., 13.])

In [4]:
np.poly([2,5,7])

array([  1., -14.,  59., -70.])